# See detect.py for explanations about the parameters
port: GPIO17
sleep_time: .002
threshold: .96
cool_down_in_s: 5
rolling_window_size: 250
telegram_bot_token: TELEGRAM_BOT_TOKEN
telegram_chat_id: TELEGRAM_CHAT_ID
log_level: INFO